### ISSUE TITLE
Do I need firebase rules to setup and run this app?

### ISSUE THREAD

**Issue by vmlinz** [luvition/MusicApp#1]
Hi,

Since I didn't see the firebase rules, do I need them to run this app?

Br,
Nick

**Comment by dattran97** [comment]
Hi Nick,
I used default rules so you don't need to setup them to run my app
Thanks for your interest 👍

**Comment by vmlinz** [comment]
@luvition Thanks very much. I will give it a try, I really love the design.

Br,
Nick
